// Generated by CoffeeScript 1.6.3
(function() {
  this.JasperReportPaginator = (function() {
    function JasperReportPaginator() {
      this.report = $('#jasper_report');
      this.pages = this.report.find('.jrPage');
      this.pagination = $('#jasper_report_container .pagination');
      this.current_page = 0;
      this.max_pages = this.pages.length;
    }

    JasperReportPaginator.prototype.show_pagination = function() {
      this.pagination.show();
      return this.show_current_page();
    };

    JasperReportPaginator.prototype.disable = function() {
      this.pagination.find('.next, .prev').addClass('disabled');
      return this.pages.show();
    };

    JasperReportPaginator.prototype.show_current_page = function() {
      if (this.has_next()) {
        this.pagination.find('.next').removeClass('disabled');
      } else {
        this.pagination.find('.next').addClass('disabled');
      }
      if (this.has_prev()) {
        this.pagination.find('.prev').removeClass('disabled');
      } else {
        this.pagination.find('.prev').addClass('disabled');
      }
      return this.pages.hide().eq(this.current_page).show();
    };

    JasperReportPaginator.prototype.next = function() {
      if (!this.has_next()) {
        return true;
      }
      this.current_page = this.current_page + 1;
      return this.show_current_page();
    };

    JasperReportPaginator.prototype.has_next = function() {
      return this.current_page < (this.max_pages - 1);
    };

    JasperReportPaginator.prototype.prev = function() {
      if (!this.has_prev()) {
        return true;
      }
      this.current_page = this.current_page - 1;
      return this.show_current_page();
    };

    JasperReportPaginator.prototype.has_prev = function() {
      return this.current_page > 0;
    };

    return JasperReportPaginator;

  })();

}).call(this);
