// Generated by CoffeeScript 1.6.3
(function() {
  $(function() {
    var paginator;
    $("#jasper_report table td > br").remove();
    paginator = new JasperReportPaginator();
    paginator.show_pagination();
    $('.jasper_report_next').click(function() {
      return paginator.next();
    });
    $('.jasper_report_prev').click(function() {
      return paginator.prev();
    });
    return $('.jasper_report_disable_pagination').click(function() {
      $(this).parent().addClass('disabled');
      return paginator.disable();
    });
  });

}).call(this);
